version: '3.2'

x-lagoon-project:
  # Lagoon project name (leave `&lagoon-project` when you edit this)
  &lagoon-project lagoon-ui-beta

x-environment: &default-environment
  LAGOON_PROJECT: *lagoon-project
  # Route that should be used locally, if you are using pygmy, this route *must* end with .docker.amazee.io
  LAGOON_ROUTE: &default-url http://lagoon-ui-beta.docker.amazee.io
  # Uncomment if you like to have the system behave like in production
  #LAGOON_ENVIRONMENT_TYPE: production
  GRAPHQL_API: "${GRAPHQL_API:-http://localhost:3000/graphql}"
  KEYCLOAK_API: "${KEYCLOAK_API:-http://localhost:8088/auth}"

services:
  ui:
    build:
      context: .
      dockerfile: .lagoon/ui.Dockerfile
    labels:
      lagoon.type: node
    # depends_on:
    #   - 'api-db'
    #   - 'api'
    # command: yarn run dev
    volumes:
      - ./services/ui/src:/app/services/ui/src
      - ./services/ui/.env.defaults:/app/services/ui/.env.defaults
      - ./services/ui/.env.schema:/app/services/ui/.env.schema
      - ./services/ui/package.json:/app/services/ui/package.json
    ports:
      - '8888:3000'
    networks:
      - amazeeio-network
      - default
    environment:
      <<: *default-environment
  api-db:
    image: uselagoon/api-db
    labels:
      lagoon.type: none
    ports:
      - '3306:3306'
    networks:
      - amazeeio-network
      - default
    environment:
      <<: *default-environment
  api:
    build:
      context: .
      dockerfile: .lagoon/api.Dockerfile
    depends_on:
      - api-db
      - keycloak
    labels:
      lagoon.type: none
    ports:
      - '3000:3000'
    volumes:
      # - ./services/api:/app/mock-data
      - ./services/api:/services/api
    # this will override the CMD in the dockerfile
    # command:
    #   - /bin/sh
    #   - -c
    #   - |
    #     cp -R /app/services/api/src /services/api
    #     rm -rf /app/services/api/src
    #     ln -sfv /services/api/src /app/services/api/src
    #     ./node_modules/.bin/tsc-watch --build --incremental --onSuccess "node -r dotenv-extended/config dist/index"
    networks:
      - amazeeio-network
      - default
    environment:
      <<: *default-environment
  api-redis:
    image: uselagoon/api-redis
    labels:
      lagoon.type: none
    environment:
      <<: *default-environment
  keycloak:
    image: uselagoon/keycloak
    user: '111111111'
    depends_on:
      - keycloak-db
    labels:
      lagoon.type: none
    ports:
      - '8088:8080'
    environment:
      <<: *default-environment
  keycloak-db:
    image: uselagoon/keycloak-db
    labels:
      lagoon.type: none
    ports:
      - '3336:3306'
    environment:
      <<: *default-environment
  local-api-data-watcher-pusher:
    build:
      context: .
      dockerfile: .lagoon/api-data-watcher-pusher.Dockerfile
    labels:
      lagoon.type: none
    depends_on:
      - api
    volumes:
      - ./local-dev/api-data:/api-data
      - ./local-dev/api-data-watcher-pusher:/home
  broker:
    image: uselagoon/broker-single
    labels:
      lagoon.type: none
    ports:
      - '15672:15672'
      - '5672:5672'
  webhook-handler:
    image: uselagoon/webhook-handler
    command: yarn run dev
    labels:
      lagoon.type: none
    ports:
      - '7777:3000'
  webhooks2tasks:
    image: uselagoon/webhooks2tasks
    command: yarn run dev
    labels:
      lagoon.type: none
  auth-server:
    image: uselagoon/auth-server
    labels:
      lagoon.type: none
    command: yarn run start
    environment:
      - JWTISSUER=auth-server.dev
      - JWTAUDIENCE=api.dev
    # volumes:
      # - ./services/auth-server/src:/app/services/auth-server/src
    ports:
      - '3001:3000'

networks:
  amazeeio-network:
    external: true
