version: '3.2'

x-lagoon-project:
  # Lagoon project name (leave `&lagoon-project` when you edit this)
  &lagoon-project lagoon-ui-beta

x-environment: &default-environment
  LAGOON_PROJECT: *lagoon-project
  # Route that should be used locally, if you are using pygmy, this route *must* end with .docker.amazee.io
  LAGOON_ROUTE: &default-url http://lagoon-ui-beta.docker.amazee.io
  # Uncomment if you like to have the system behave like in production
  #LAGOON_ENVIRONMENT_TYPE: production
  #GRAPHQL_API: "${GRAPHQL_API:-http://localhost:3000/graphql}"
  #KEYCLOAK_API: "${KEYCLOAK_API:-http://localhost:8088/auth}"

services:
  ui:
    build:
      context: .
      dockerfile: .lagoon/ui.Dockerfile
    labels:
      lagoon.type: node
    depends_on:
      - 'api-db'
      - 'api'
    command: yarn run start
    env_file: ./services/ui/.env.defaults
    volumes:
      - ./services/ui/src:/app/services/ui/src
      - ./services/ui/.env.defaults:/app/services/ui/.env.defaults
      - ./services/ui/.env.schema:/app/services/ui/.env.schema
      - ./services/ui/package.json:/app/services/ui/package.json
    ports:
      - '3003:3003'
    networks:
      - amazeeio-network
      - default
    environment:
      <<: *default-environment
      LAGOON_LOCALDEV_HTTP_PORT: 3003
  api-db:
    image: uselagoon/api-db
    labels:
      lagoon.type: none
    ports:
      - '3306:3306'
    networks:
      - amazeeio-network
      - default
    environment:
      <<: *default-environment
  api:
    build:
      context: .
      dockerfile: .lagoon/api.Dockerfile
    depends_on:
      - api-db
      - keycloak
    labels:
      lagoon.type: none
    ports:
      - '3000:3000'
    volumes:
      - ./services/api:/services/api
      - ./services/mock-data:/mock-data
    networks:
      - amazeeio-network
      - default
    environment:
      <<: *default-environment
  api-redis:
    image: uselagoon/api-redis
    labels:
      lagoon.type: none
    environment:
      <<: *default-environment
  keycloak:
    build:
      context: .
      dockerfile: .lagoon/keycloak.Dockerfile
    user: '111111111'
    depends_on:
      - keycloak-db
    labels:
      lagoon.type: none
    volumes:
      - .lagoon/start.sh:/opt/jboss/tools/start.sh
    ports:
      - '8088:8080'
    environment:
      <<: *default-environment
  keycloak-db:
    image: uselagoon/keycloak-db
    labels:
      lagoon.type: none
    ports:
      - '3336:3306'
    environment:
      <<: *default-environment
  local-api-data-watcher-pusher:
    build:
      context: .
      dockerfile: .lagoon/api-data-watcher-pusher.Dockerfile
    labels:
      lagoon.type: none
    depends_on:
      - api
    volumes:
      - ./local-dev/api-data:/api-data
      - ./local-dev/api-data-watcher-pusher:/home

networks:
  amazeeio-network:
    external: true
